export const UPLOAD_NEWRECIPE_START = 'UPLOAD_NEWRECIPE_START';
export const UPLOAD_NEWRECIPE_SUCCESS = 'UPLOAD_NEWRECIPE_SUCCESS';
export const UPLOAD_NEWRECIPE_FAIL = 'UPLOAD_NEWRECIPE_FAIL';

export const FETCH_RECIPES_START = 'FETCH_RECIPES_START';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';